BEGIN;

-- =========================================================
-- Códigos temporales para reiniciar aprobaciones
-- =========================================================

CREATE TABLE IF NOT EXISTS public.codigos_reinicio_aprobaciones (
  codigo_reinicio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  inspecciones_id BIGINT NOT NULL,
  tipo_inspeccion TEXT NOT NULL,

  codigo_hash TEXT NOT NULL,
  codigo_salt TEXT NOT NULL,

  vence_en TIMESTAMPTZ NOT NULL,
  intentos SMALLINT NOT NULL DEFAULT 0,

  usado_en TIMESTAMPTZ NULL,
  invalidado_en TIMESTAMPTZ NULL,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT codigos_reinicio_inspeccion_fkey
    FOREIGN KEY (inspecciones_id)
    REFERENCES public.inspecciones(inspecciones_id)
    ON DELETE CASCADE,

  CONSTRAINT codigos_reinicio_tipo_check
    CHECK (tipo_inspeccion IN ('SST', 'EPP')),

  CONSTRAINT codigos_reinicio_intentos_check
    CHECK (intentos >= 0 AND intentos <= 5),

  CONSTRAINT codigos_reinicio_vencimiento_check
    CHECK (vence_en > creado_en)
);

CREATE INDEX IF NOT EXISTS codigos_reinicio_busqueda_idx
  ON public.codigos_reinicio_aprobaciones (
    inspecciones_id,
    tipo_inspeccion,
    creado_en DESC
  );

CREATE UNIQUE INDEX IF NOT EXISTS codigos_reinicio_unico_activo_idx
  ON public.codigos_reinicio_aprobaciones (
    inspecciones_id,
    tipo_inspeccion
  )
  WHERE usado_en IS NULL
    AND invalidado_en IS NULL;

COMMIT;